name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Run tests with coverage
      run: |
        coverage run --source=src -m unittest discover -s tests
        coverage report --fail-under=90  # This will fail the job if coverage is below 90%
    - name: Generate coverage HTML report
      run: coverage html

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()

    steps:
    - name: Simulate Deployment
      run: echo "Deploying application to production environment..."

